include: package:lint/analysis_options_package.yaml

analyzer:
  exclude:
    - 'lib/**/*.g.dart'
    - 'tests/'
    - 'test_driver/'
    - 'packages/'
  errors:
#    invalid_use_of_protected_member: error
    avoid_relative_lib_imports: error
    use_build_context_synchronously: ignore
    avoid_slow_async_io: error
    avoid_types_as_parameter_names: error
    valid_regexps: error
    always_require_non_null_named_parameters: error

linter:
  rules:
    avoid_classes_with_only_static_members: false
    avoid_multiple_declarations_per_line: false
    avoid_positional_boolean_parameters: false
    void_checks: false
    unawaited_futures: false
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false
    use_setters_to_change_properties: false
    prefer_double_quotes: false
    prefer_final_fields: false
    require_trailing_commas: true
    file_names: false
