workflows:
  ios-workflow:
    name: iOS Workflow
    # TODO Ilya: mac_mini_m1
    # instance_type: mac_mini
    max_build_duration: 120
    environment:
      groups:
        - app_store_credentials # <-- (Includes APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY, CERTIFICATE_PRIVATE_KEY) - https://docs.codemagic.io/code-signing-yaml/signing-ios/
        - ios_config # <-- (Includes APP_STORE_ID)
        # Add the above group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
      vars:
        XCODE_WORKSPACE: 'Runner.xcworkspace'
        XCODE_SCHEME: 'Runner'
        BUNDLE_ID: 'app.rateclub.rateClub'
      flutter: 2.5.3
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: release
      cancel_previous_builds: true
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
                    keychain initialize
      - name: Fetch signing files
        script: |
                    app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
      - name: Use system default keychain
        script: |
                    keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
                    xcode-project use-profiles
      - name: Get Flutter packages
        script: |
                    cd . && flutter packages pub get
#      - name: Flutter analyze
#        script: |
#                    cd . && flutter analyze
      - name: Flutter unit tests
        script: |
                    cd . && flutter test
        ignore_failure: true
      - name: Install pods
        script: |
                    find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and automatic versioning
        # --bundle-sksl-path flutter_01.sksl.json \
        script: |
          flutter build ipa --release \
          --build-name=1.0.0 \
          --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1)) \
          --export-options-plist=/Users/builder/export_options.plist          
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      # See the following link for details about email publishing - https://docs.codemagic.io/yaml-publishing/email
      email:
        recipients:
          - iliyazelenkog@gmail.com
        notify:
          success: true # To receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails
#      slack:
#        # See the following link about how to connect your Slack account - https://docs.codemagic.io/yaml-publishing/slack
#        channel: '#builds'
#        notify_on_build_start: true # To receive a notification when a build starts
#        notify:
#          success: true # To receive a notification when a build succeeds
#          failure: false # To not receive a notification when a build fails
      app_store_connect: # https://docs.codemagic.io/yaml-publishing/app-store-connect
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - rateclub
