name: profile
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependency_overrides:
  async: 2.6.1

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.3.0
  worker_manager: 4.2.6
  equatable: ^2.0.3
  rate_club:
    path: "../../"

dev_dependencies:
  test: ^1.16.8
  json_serializable: ^6.0.0
  build_runner: ^2.1.4

