name: feed
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.14.4 <3.0.0'

dependency_overrides:
  async: 2.6.1

dependencies:
  worker_manager: 4.2.6
  equatable: 2.0.3
  flutter:
    sdk: flutter
  rate_club:
    path: "../../"

dev_dependencies:
  build_runner: 2.1.4
  flutter_test:
    sdk: flutter
