import 'package:flutter/widgets.dart';
import 'package:flutter_svg/flutter_svg.dart';

import 'icon_interface.dart';

// THIS FILE IS AUTO-GENERATED by rate_club/scripts/icons_generator.py

class IconSocialYouTube extends StatelessWidget implements IconInterface {
  final double? height;
  final double? width;
  final double? size;
  final Color? color;

  static const _svgString = '''
	<svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M0 20C0 8.95431 8.95431 0 20 0C31.0457 0 40 8.95431 40 20C40 31.0457 31.0457 40 20 40C8.95431 40 0 31.0457 0 20Z" fill="black"/><path d="M31.5057 14.6293C31.2289 13.6013 30.4184 12.7908 29.3904 12.514C27.5123 12 19.9999 12 19.9999 12C19.9999 12 12.4876 12 10.6095 12.4942C9.60131 12.771 8.771 13.6013 8.49423 14.6293C8 16.5074 8 20.4019 8 20.4019C8 20.4019 8 24.3163 8.49423 26.1746C8.771 27.2026 9.58154 28.0131 10.6095 28.2899C12.5074 28.8039 19.9999 28.8039 19.9999 28.8039C19.9999 28.8039 27.5123 28.8039 29.3904 28.3097C30.4184 28.0329 31.2289 27.2223 31.5057 26.1943C31.9999 24.3163 31.9999 20.4217 31.9999 20.4217C31.9999 20.4217 32.0197 16.5074 31.5057 14.6293Z" fill="white"/><path d="M17.6079 23.9997L23.855 20.4017L17.6079 16.8037V23.9997Z" fill="black"/></svg>
    ''';

  const IconSocialYouTube({Key? key, this.height, this.width, this.size, this.color}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SvgPicture.string(
      _svgString,
      color: color,
      height: size ?? height,
      width: size ?? width,
    );
  }
}

    