import 'package:flutter/widgets.dart';
import 'package:flutter_svg/flutter_svg.dart';

import 'icon_interface.dart';

// THIS FILE IS AUTO-GENERATED by rate_club/scripts/icons_generator.py

class IconSocialFacebookMessenger extends StatelessWidget implements IconInterface {
  final double? height;
  final double? width;
  final double? size;
  final Color? color;

  static const _svgString = '''
	<svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M0 20C0 8.95431 8.95431 0 20 0C31.0457 0 40 8.95431 40 20C40 31.0457 31.0457 40 20 40C8.95431 40 0 31.0457 0 20Z" fill="black"/><path fill-rule="evenodd" clip-rule="evenodd" d="M6.64307 19.5979C6.64307 12.1547 12.4767 6.6416 20.0001 6.6416C27.5234 6.6416 33.3571 12.1581 33.3571 19.6013C33.3571 27.0445 27.5234 32.5576 20.0001 32.5576C18.6477 32.5576 17.3521 32.3772 16.1332 32.0433C15.8961 31.9799 15.6424 31.9966 15.4186 32.0968L12.7673 33.2655C12.0727 33.5727 11.2913 33.0785 11.2679 32.3205L11.1945 29.9429C11.1878 29.6491 11.0542 29.3753 10.8372 29.1816C8.23923 26.8575 6.64307 23.4915 6.64307 19.5979ZM15.9026 17.1636L11.979 23.388C11.6016 23.9857 12.3363 24.6569 12.8973 24.2295L17.1114 21.0305C17.3952 20.8134 17.7893 20.8134 18.0764 21.0271L21.1986 23.3679C22.137 24.0692 23.4727 23.8254 24.0971 22.8337L28.0241 16.6126C28.3981 16.0149 27.6634 15.3404 27.1024 15.7678L22.8883 18.9668C22.6045 19.1839 22.2104 19.1839 21.9232 18.9701L18.801 16.6293C17.8627 15.9281 16.527 16.1718 15.9026 17.1636Z" fill="white"/></svg>
    ''';

  const IconSocialFacebookMessenger({Key? key, this.height, this.width, this.size, this.color}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SvgPicture.string(
      _svgString,
      color: color,
      height: size ?? height,
      width: size ?? width,
    );
  }
}

    