import 'package:flutter/widgets.dart';
import 'package:flutter_svg/flutter_svg.dart';

import 'icon_interface.dart';

// THIS FILE IS AUTO-GENERATED by rate_club/scripts/icons_generator.py

class IconSocialTwitter extends StatelessWidget implements IconInterface {
  final double? height;
  final double? width;
  final double? size;
  final Color? color;

  static const _svgString = '''
	<svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M0 20C0 8.95431 8.95431 0 20 0C31.0457 0 40 8.95431 40 20C40 31.0457 31.0457 40 20 40C8.95431 40 0 31.0457 0 20Z" fill="black"/><path d="M16.34 30.5502C25.21 30.5502 30.06 23.2002 30.06 16.8302C30.06 16.6202 30.06 16.4102 30.05 16.2102C30.99 15.5302 31.81 14.6802 32.46 13.7102C31.6 14.0902 30.67 14.3502 29.69 14.4702C30.69 13.8702 31.45 12.9302 31.81 11.8002C30.88 12.3502 29.85 12.7502 28.75 12.9702C27.87 12.0302 26.62 11.4502 25.23 11.4502C22.57 11.4502 20.41 13.6102 20.41 16.2702C20.41 16.6502 20.45 17.0202 20.54 17.3702C16.53 17.1702 12.98 15.2502 10.6 12.3302C10.19 13.0402 9.94997 13.8702 9.94997 14.7502C9.94997 16.4202 10.8 17.9002 12.1 18.7602C11.31 18.7402 10.57 18.5202 9.91997 18.1602C9.91997 18.1802 9.91997 18.2002 9.91997 18.2202C9.91997 20.5602 11.58 22.5002 13.79 22.9502C13.39 23.0602 12.96 23.1202 12.52 23.1202C12.21 23.1202 11.91 23.0902 11.61 23.0302C12.22 24.9502 14 26.3402 16.11 26.3802C14.46 27.6702 12.38 28.4402 10.12 28.4402C9.72997 28.4402 9.34997 28.4202 8.96997 28.3702C11.08 29.7502 13.62 30.5502 16.34 30.5502Z" fill="white"/></svg>
    ''';

  const IconSocialTwitter({Key? key, this.height, this.width, this.size, this.color}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SvgPicture.string(
      _svgString,
      color: color,
      height: size ?? height,
      width: size ?? width,
    );
  }
}

    