import 'package:flutter/widgets.dart';
import 'package:flutter_svg/flutter_svg.dart';

import 'icon_interface.dart';

// THIS FILE IS AUTO-GENERATED by rate_club/scripts/icons_generator.py

class IconSocialGoogle extends StatelessWidget implements IconInterface {
  final double? height;
  final double? width;
  final double? size;
  final Color? color;

  static const _svgString = '''
	<svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M0 20C0 8.95431 8.95431 0 20 0C31.0457 0 40 8.95431 40 20C40 31.0457 31.0457 40 20 40C8.95431 40 0 31.0457 0 20Z" fill="black"/><path fill-rule="evenodd" clip-rule="evenodd" d="M32 20.2674C32 19.4303 31.9249 18.6253 31.7854 17.8525H20.6661V22.4194H27.02C26.7463 23.8951 25.9145 25.1455 24.6641 25.9827V28.9449H28.4796C30.7121 26.8896 32 23.8629 32 20.2674Z" fill="white"/><path fill-rule="evenodd" clip-rule="evenodd" d="M20.6661 31.8061C23.8538 31.8061 26.5262 30.7489 28.4796 28.9458L24.6641 25.9836C23.6069 26.6919 22.2546 27.1105 20.6661 27.1105C17.5911 27.1105 14.9884 25.0337 14.06 22.2432H10.1157V25.302C12.0584 29.1605 16.051 31.8061 20.6661 31.8061Z" fill="white"/><path fill-rule="evenodd" clip-rule="evenodd" d="M14.06 22.2425C13.8239 21.5341 13.6898 20.7774 13.6898 19.9993C13.6898 19.2212 13.8239 18.4645 14.06 17.7561V14.6973H10.1157C9.31613 16.2911 8.85999 18.0942 8.85999 19.9993C8.85999 21.9044 9.31613 23.7075 10.1157 25.3013L14.06 22.2425Z" fill="white"/><path fill-rule="evenodd" clip-rule="evenodd" d="M20.6661 12.889C22.3995 12.889 23.9557 13.4847 25.1793 14.6545L28.5655 11.2683C26.5209 9.36324 23.8484 8.19336 20.6661 8.19336C16.051 8.19336 12.0584 10.839 10.1157 14.6975L14.06 17.7563C14.9884 14.9658 17.5911 12.889 20.6661 12.889Z" fill="white"/></svg>
    ''';

  const IconSocialGoogle({Key? key, this.height, this.width, this.size, this.color}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SvgPicture.string(
      _svgString,
      color: color,
      height: size ?? height,
      width: size ?? width,
    );
  }
}

    