import 'package:flutter/widgets.dart';
import 'package:flutter_svg/flutter_svg.dart';

import 'icon_interface.dart';

// THIS FILE IS AUTO-GENERATED by rate_club/scripts/icons_generator.py

class IconChevronUp extends StatelessWidget implements IconInterface {
  final double? height;
  final double? width;
  final double? size;
  final Color? color;

  static const _svgString = '''
	<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M7 14L8.74731 12.237C10.1408 10.8311 10.8375 10.1281 11.6867 10.0199C11.8947 9.99337 12.1053 9.99337 12.3133 10.0199C13.1625 10.1281 13.8592 10.8311 15.2527 12.237L17 14" stroke="#5B5A69" stroke-width="1.5" stroke-linecap="round"/></svg>
    ''';

  const IconChevronUp({Key? key, this.height, this.width, this.size, this.color}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SvgPicture.string(
      _svgString,
      color: color,
      height: size ?? height,
      width: size ?? width,
    );
  }
}

    