import 'package:flutter/widgets.dart';
import 'package:flutter_svg/flutter_svg.dart';

import 'icon_interface.dart';

// THIS FILE IS AUTO-GENERATED by rate_club/scripts/icons_generator.py

class IconFilter extends StatelessWidget implements IconInterface {
  final double? height;
  final double? width;
  final double? size;
  final Color? color;

  static const _svgString = '''
	<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M3 6.47246C3 4.55467 4.55467 3 6.47246 3H17.5842C19.4707 3 21 4.52929 21 6.41577C21 7.42052 20.5576 8.37431 19.7906 9.02332L16.2703 12.0021C15.1475 12.9521 14.5 14.3482 14.5 15.819V17.5996C14.5 18.4795 14.079 19.3062 13.3675 19.8237L11.4262 21.2355C10.4165 21.9698 9 21.2485 9 20V15.6995C9 14.298 8.41177 12.9608 7.37862 12.0137L4.12603 9.0322C3.40852 8.37448 3 7.44581 3 6.47246Z" fill="#CED7FA" stroke="#5B5A69" stroke-width="1.5"/></svg>
    ''';

  const IconFilter({Key? key, this.height, this.width, this.size, this.color}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SvgPicture.string(
      _svgString,
      color: color,
      height: size ?? height,
      width: size ?? width,
    );
  }
}

    