import 'package:flutter/widgets.dart';
import 'package:flutter_svg/flutter_svg.dart';

import 'icon_interface.dart';

// THIS FILE IS AUTO-GENERATED by rate_club/scripts/icons_generator.py

class IconSocialTwitch extends StatelessWidget implements IconInterface {
  final double? height;
  final double? width;
  final double? size;
  final Color? color;

  static const _svgString = '''
	<svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M0 20C0 8.95431 8.95431 0 20 0C31.0457 0 40 8.95431 40 20C40 31.0457 31.0457 40 20 40C8.95431 40 0 31.0457 0 20Z" fill="black"/><path d="M29.226 20.361L25.7303 23.8566H22.2347L19.1761 26.9152V23.8566H15.2435V10.748H29.226V20.361Z" fill="black"/><path d="M14.3695 9L10 13.3695V29.0997H15.2434V33.4692L19.6129 29.0997H23.1085L30.9736 21.2346V9H14.3695ZM29.2258 20.3607L25.7302 23.8563H22.2346L19.176 26.915V23.8563H15.2434V10.7478H29.2258V20.3607Z" fill="white"/><path d="M26.604 13.8066H24.8562V19.05H26.604V13.8066Z" fill="white"/><path d="M21.7976 13.8066H20.0498V19.05H21.7976V13.8066Z" fill="white"/></svg>
    ''';

  const IconSocialTwitch({Key? key, this.height, this.width, this.size, this.color}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SvgPicture.string(
      _svgString,
      color: color,
      height: size ?? height,
      width: size ?? width,
    );
  }
}

    