name: app_http_client
description: Http client.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependency_overrides:
  async: 2.6.1

dependencies:
  jwt_decoder: 2.0.1
  rate_club:
    path: "../../"
