name: app_http_client
description: Http client.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.14.4 <3.0.0"

dependency_overrides:
  async: 2.6.1

dependencies:
  dio: ^4.0.6
  isolated_http_client: 1.5.6
  worker_manager: 4.2.6
  jwt_decoder: 2.0.1
  rate_club:
    path: "../../"
